# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.recipient_details_request import RecipientDetailsRequest

class TestRecipientDetailsRequest(unittest.TestCase):
    """RecipientDetailsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecipientDetailsRequest:
        """Test RecipientDetailsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecipientDetailsRequest`
        """
        model = RecipientDetailsRequest()
        if include_optional:
            return RecipientDetailsRequest(
                address = openapi_client.models.address_request.AddressRequest(
                    full_name = '', 
                    company_name = '', 
                    address_line1 = '', 
                    address_line2 = '', 
                    address_line3 = '', 
                    city = '', 
                    county = '', 
                    postcode = '', 
                    country_code = '', ),
                phone_number = '',
                email_address = '',
                address_book_reference = ''
            )
        else:
            return RecipientDetailsRequest(
        )
        """

    def testRecipientDetailsRequest(self):
        """Test RecipientDetailsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
