# coding: utf-8

# flake8: noqa

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.labels_api import LabelsApi
from openapi_client.api.manifests_api import ManifestsApi
from openapi_client.api.orders_api import OrdersApi
from openapi_client.api.version_api import VersionApi

# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.models.address_request import AddressRequest
from openapi_client.models.billing_details_request import BillingDetailsRequest
from openapi_client.models.create_order_error_response import CreateOrderErrorResponse
from openapi_client.models.create_order_label_error_response import CreateOrderLabelErrorResponse
from openapi_client.models.create_order_request import CreateOrderRequest
from openapi_client.models.create_order_response import CreateOrderResponse
from openapi_client.models.create_orders_request import CreateOrdersRequest
from openapi_client.models.create_orders_response import CreateOrdersResponse
from openapi_client.models.delete_orders_resource import DeleteOrdersResource
from openapi_client.models.deleted_order_info import DeletedOrderInfo
from openapi_client.models.dimensions_request import DimensionsRequest
from openapi_client.models.error_response import ErrorResponse
from openapi_client.models.failed_order_response import FailedOrderResponse
from openapi_client.models.get_order_details_resource import GetOrderDetailsResource
from openapi_client.models.get_order_info_resource import GetOrderInfoResource
from openapi_client.models.get_order_line_result import GetOrderLineResult
from openapi_client.models.get_orders_details_response import GetOrdersDetailsResponse
from openapi_client.models.get_orders_response import GetOrdersResponse
from openapi_client.models.get_postal_details_result import GetPostalDetailsResult
from openapi_client.models.get_shipping_details_result import GetShippingDetailsResult
from openapi_client.models.get_tag_details_result import GetTagDetailsResult
from openapi_client.models.get_version_resource import GetVersionResource
from openapi_client.models.importer import Importer
from openapi_client.models.label_generation_request import LabelGenerationRequest
from openapi_client.models.manifest_details_response import ManifestDetailsResponse
from openapi_client.models.manifest_errors_error_details_response import ManifestErrorsErrorDetailsResponse
from openapi_client.models.manifest_errors_response import ManifestErrorsResponse
from openapi_client.models.manifest_orders_response import ManifestOrdersResponse
from openapi_client.models.order_error_info import OrderErrorInfo
from openapi_client.models.order_error_response import OrderErrorResponse
from openapi_client.models.order_field_response import OrderFieldResponse
from openapi_client.models.order_update_error import OrderUpdateError
from openapi_client.models.postage_details_request import PostageDetailsRequest
from openapi_client.models.product_item_request import ProductItemRequest
from openapi_client.models.recipient_details_request import RecipientDetailsRequest
from openapi_client.models.sender_details_request import SenderDetailsRequest
from openapi_client.models.shipment_package_request import ShipmentPackageRequest
from openapi_client.models.tag_request import TagRequest
from openapi_client.models.update_order_status_request import UpdateOrderStatusRequest
from openapi_client.models.update_order_status_response import UpdateOrderStatusResponse
from openapi_client.models.update_orders_status_request import UpdateOrdersStatusRequest
from openapi_client.models.updated_order_info import UpdatedOrderInfo
